"""scripts/diagnose.py
============================
ComfyUI Auto Node Disable —— 独立可运行的复现 / 诊断入口。

目的
----
在没有 ComfyUI 宿主的情况下演练本插件的核心路径，并输出可关联到
``auto_disable.py`` 中具体决策步骤的结构化诊断信息，便于：

* 在没有 ComfyUI 服务的环境中回归核心逻辑；
* 在真实生产环境出现"为什么 X 模块被禁用 / 没被禁用"等问题时，
  把脚本当作诊断器逐步还原现场。

设计
----
脚本本身不修改 ``auto_disable`` 的产品行为，只在以下两点上接入：

1. 通过 ``sys.modules['nodes']`` 注入一个伪造的 ``nodes`` 模块，
   让 ``auto_disable._custom_nodes_dir()`` 与 ``_scan_known_modules()``
   能够找到 ``custom_nodes`` 根目录与全局节点映射；
2. 在临时目录里按真实结构摆好 ``custom_nodes/<name>/`` 与
   ``custom_nodes/.disabled/``，使 ``_disable_module`` 与
   ``restore_module`` 的副作用落在隔离的临时树里。

输出
----
每个关键动作都用 ``[STEP X.Y]`` 标号 + 关键字段 + 结论的形式打印。
运行本脚本后即可根据 STEP 编号在 ``auto_disable.py`` 中定位到对应的
函数 / 分支（例如 ``[STEP 3.4]`` 对应 ``_decide`` 中的
"if node_classes.isdisjoint(used_union)" 分支）。

运行方式
--------
::

    python scripts/diagnose.py
    python scripts/diagnose.py --scenario failure      # 只跑失败场景
    python scripts/diagnose.py --scenario restore      # 只跑恢复场景
    python scripts/diagnose.py --scenario normal       # 只跑正常场景

依赖
----
仅 Python 标准库。脚本退出时会清理临时目录与 ``sys.modules['nodes']``。
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
import time
import types
from typing import Any, Iterable


HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HERE)

# 把项目根目录加入 path，让脚本无论从哪个 cwd 启动都能 import auto_disable。
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import auto_disable  # noqa: E402  必须在 sys.path 调整之后


# ---------------------------------------------------------------------------
# 输出工具
# ---------------------------------------------------------------------------

def _emit(step: str, title: str, *, fields: dict[str, Any] | None = None,
          result: str | None = None) -> None:
    """以固定结构打印一个诊断步骤。

    :param step: 例如 ``"1.2"``，最终输出为 ``[STEP 1.2]``
    :param title: 简要说明当前步骤做了什么
    :param fields: 关键字段，例如路径、状态快照、决策参数
    :param result: 结论，例如 ``"OK"`` / ``"SKIPPED"`` / ``"FAIL: ..."``
    """
    print(f"[STEP {step}] {title}")
    if fields:
        width = max((len(k) for k in fields), default=0)
        for k, v in fields.items():
            if isinstance(v, (dict, list)):
                v_repr = json.dumps(v, ensure_ascii=False, sort_keys=True)
            else:
                v_repr = str(v)
            print(f"    {k.ljust(width)} = {v_repr}")
    if result is not None:
        print(f"    -> {result}")
    print()


# ---------------------------------------------------------------------------
# 临时宿主环境
# ---------------------------------------------------------------------------

class _FakeNodeClass:
    """伪造的节点类，仅承载 ``RELATIVE_PYTHON_MODULE`` 元信息。"""

    def __init__(self, rel_module: str) -> None:
        self.RELATIVE_PYTHON_MODULE = rel_module


class _FakeComfyEnv:
    """在临时目录里构造一个最小的 ComfyUI 根，并安装到 ``sys.modules``。

    退出时 ``close()`` 会恢复原始的 ``nodes`` 模块和临时目录。
    """

    def __init__(self, step_prefix: str) -> None:
        self.step_prefix = step_prefix
        self.tmp_root = tempfile.mkdtemp(prefix="auto_disable_diag_")
        self.comfy_root = os.path.join(self.tmp_root, "comfy_root")
        self.custom_nodes_dir = os.path.join(self.comfy_root, "custom_nodes")
        self.disabled_dir = os.path.join(self.custom_nodes_dir, ".disabled")
        os.makedirs(self.custom_nodes_dir, exist_ok=True)
        os.makedirs(self.disabled_dir, exist_ok=True)

        # 让 auto_disable._state_path() 把状态文件落在我们的临时目录里，
        # 而不是进程的 cwd / 真实 ComfyUI 根。
        # 状态文件名跟随产品常量（2026-08-17 起从 ``.json`` 迁到 ``.db``）。
        self.state_path = os.path.join(self.comfy_root, auto_disable.STATE_FILENAME)

        self._original_nodes = sys.modules.get("nodes")
        self._original_state_path_factory = auto_disable._state_path

        # ---- 构造伪 nodes.py ----
        nodes_file = os.path.join(self.comfy_root, "nodes.py")
        with open(nodes_file, "w", encoding="utf-8") as f:
            f.write("# auto-generated by scripts/diagnose.py\n")
            f.write("NODE_CLASS_MAPPINGS = {}\n")

        nodes_mod = types.ModuleType("nodes")
        nodes_mod.__file__ = nodes_file
        nodes_mod.NODE_CLASS_MAPPINGS: dict[str, _FakeNodeClass] = {}
        sys.modules["nodes"] = nodes_mod

        # ---- 重写 auto_disable 的两个只读函数 ----
        def _custom_nodes_dir_override() -> str:
            return self.custom_nodes_dir

        def _state_path_override() -> str:
            return self.state_path

        auto_disable._custom_nodes_dir = _custom_nodes_dir_override  # type: ignore[assignment]
        auto_disable._state_path = _state_path_override  # type: ignore[assignment]
        # _comfy_root / _disabled_dir 都是从 _custom_nodes_dir 派生的，
        # 自动跟随上述替换，脚本无需再覆盖。

        _emit(
            f"{self.step_prefix}.1",
            "构造隔离的伪 ComfyUI 根并注入 sys.modules['nodes']",
            fields={
                "tmp_root": self.tmp_root,
                "comfy_root": self.comfy_root,
                "custom_nodes_dir": self.custom_nodes_dir,
                "state_path": self.state_path,
                "real_comfy_root": auto_disable._comfy_root(),
                "real_state_path": auto_disable._state_path(),
            },
            result="OK",
        )

    # ------------------------------------------------------------------ API

    def add_node(self, class_name: str, module_name: str) -> None:
        """向 ``NODE_CLASS_MAPPINGS`` 注册一个属于 ``module_name`` 的节点类。"""
        rel = f"custom_nodes.{module_name}"
        cls = _FakeNodeClass(rel)
        sys.modules["nodes"].NODE_CLASS_MAPPINGS[class_name] = cls

    def make_module(self, name: str) -> str:
        """在 ``custom_nodes/<name>/`` 下创建一个空包目录，返回绝对路径。"""
        path = os.path.join(self.custom_nodes_dir, name)
        os.makedirs(path, exist_ok=True)
        init_py = os.path.join(path, "__init__.py")
        if not os.path.exists(init_py):
            with open(init_py, "w", encoding="utf-8") as f:
                f.write("# placeholder for diagnose.py\n")
        return path

    def rm_module(self, name: str) -> None:
        """物理删除一个模块目录，用于构造"路径缺失"失败场景。"""
        path = os.path.join(self.custom_nodes_dir, name)
        if os.path.isdir(path):
            shutil.rmtree(path)

    def list_custom_nodes(self) -> list[str]:
        return sorted(
            d for d in os.listdir(self.custom_nodes_dir)
            if os.path.isdir(os.path.join(self.custom_nodes_dir, d))
            and d != ".disabled"
        )

    def disabled_targets(self) -> list[str]:
        if not os.path.isdir(self.disabled_dir):
            return []
        return sorted(os.listdir(self.disabled_dir))

    def snapshot_state(self) -> dict[str, Any]:
        return auto_disable.snapshot()

    def close(self) -> None:
        # 恢复 sys.modules 与 auto_disable 函数指针
        if self._original_nodes is not None:
            sys.modules["nodes"] = self._original_nodes
        else:
            sys.modules.pop("nodes", None)
        auto_disable._custom_nodes_dir = (  # type: ignore[assignment]
            lambda: _real_custom_nodes_dir()
        )
        auto_disable._state_path = self._original_state_path_factory  # type: ignore[assignment]
        shutil.rmtree(self.tmp_root, ignore_errors=True)


def _real_custom_nodes_dir() -> str:
    """``close()`` 之后 ``auto_disable`` 回到原始实现。"""
    try:
        import nodes  # type: ignore
        return os.path.join(os.path.dirname(os.path.abspath(nodes.__file__)), "custom_nodes")
    except Exception:
        return os.path.join(os.environ.get("COMFYUI_PATH", os.getcwd()), "custom_nodes")


# ---------------------------------------------------------------------------
# 场景 1：正常禁用流程
# ---------------------------------------------------------------------------

def scenario_normal() -> dict[str, Any]:
    """三次入队都用不到 ``unused_pkg``，预期它会被自动移动到 ``.disabled``。"""
    step = "1"
    env = _FakeComfyEnv(step_prefix=step)

    # ---- 1.2 安装两个模块 ----
    env.make_module("kept_pkg")        # 始终被使用
    env.make_module("unused_pkg")      # 始终不被使用
    env.add_node("KeptNode", "kept_pkg")
    env.add_node("UnusedNode", "unused_pkg")
    _emit(
        f"{step}.2",
        "注册两个 custom_node 模块（kept_pkg / unused_pkg）",
        fields={
            "known_modules(before scan)": {},
            "custom_nodes_dir_listing": env.list_custom_nodes(),
        },
        result="OK",
    )

    # ---- 1.3 模拟首次入队（带 ON_PROMPT 钩子提取节点类的同样路径）----
    used = auto_disable.extract_used_class_names(
        {"prompt": {"1": {"class_type": "KeptNode", "inputs": {}}}}
    )
    auto_disable.record_prompt(used)
    # 注意：auto_disable._decide 在 rounds 不足 threshold 时取 "全部 rounds" 作为
    # recent，所以单次入队也可能触发禁用；脚本注释如实反映这一行为。
    snap = env.snapshot_state()
    _emit(
        f"{step}.3",
        "第 1 次入队（仅使用 KeptNode）；rounds<threshold 时 _decide 用全部 rounds",
        fields={
            "used_classes": used,
            "rounds_len": len(snap["rounds"]),
            "disabled_after": list(snap["disabled"].keys()),
            "known_modules": sorted(snap["known_modules"].keys()),
        },
        result=(
            "disabled_count>=1 (rounds<threshold 时 recent=rounds)"
            if snap["disabled"] else "disabled_count=0"
        ),
    )

    # ---- 1.4 第 2 次入队 ----
    auto_disable.record_prompt(used)
    snap = env.snapshot_state()
    _emit(
        f"{step}.4",
        "第 2 次入队（仍然只用 KeptNode）",
        fields={
            "rounds_len": len(snap["rounds"]),
            "disabled_after": list(snap["disabled"].keys()),
        },
        result=(
            f"disabled_count={len(snap['disabled'])} (累计)"
        ),
    )

    # ---- 1.5 第 N 次入队：触发 _decide 命中 ----
    before_listing = env.list_custom_nodes()
    auto_disable.record_prompt(used)
    snap = env.snapshot_state()
    after_listing = env.list_custom_nodes()
    _emit(
        f"{step}.5",
        "第 3 次入队：_decide 命中阈值，unused_pkg 应被移动",
        fields={
            "rounds_len": len(snap["rounds"]),
            "used_union_recent": sorted(
                set().union(*(r["used_classes"] for r in snap["rounds"][-3:]))
            ),
            "disabled_after": list(snap["disabled"].keys()),
            "custom_nodes_dir_before": before_listing,
            "custom_nodes_dir_after": after_listing,
            "disabled_dir_listing": env.disabled_targets(),
        },
        result=(
            "OK" if "unused_pkg" in env.disabled_targets() else "FAIL: 未触发移动"
        ),
    )

    # ---- 1.6 二次 _decide 不应重复禁用 ----
    auto_disable.record_prompt(used)
    snap = env.snapshot_state()
    _emit(
        f"{step}.6",
        "继续入队：已被禁用的模块应被 _decide 跳过",
        fields={
            "disabled_after": list(snap["disabled"].keys()),
            "disabled_dir_listing": env.disabled_targets(),
        },
        result="OK (disabled 计数保持 1)",
    )

    summary = {
        "scenario": "normal",
        "final_disabled": list(snap["disabled"].keys()),
        "disabled_dir": env.disabled_targets(),
        "kept_pkg_present": "kept_pkg" in env.list_custom_nodes(),
    }
    env.close()
    return summary


# ---------------------------------------------------------------------------
# 场景 2：恢复流程
# ---------------------------------------------------------------------------

def scenario_restore() -> dict[str, Any]:
    step = "2"
    env = _FakeComfyEnv(step_prefix=step)
    env.make_module("revive_pkg")
    env.add_node("ReviveNode", "revive_pkg")

    # ---- 2.2 触发禁用 ----
    for _ in range(3):
        auto_disable.record_prompt([])  # 完全空 prompt：所有已知模块都会被禁用
    snap = env.snapshot_state()
    _emit(
        f"{step}.2",
        "空入队 3 次以触发禁用",
        fields={
            "disabled_after": list(snap["disabled"].keys()),
            "custom_nodes_dir": env.list_custom_nodes(),
            "disabled_dir": env.disabled_targets(),
        },
        result="OK" if "revive_pkg" in env.disabled_targets() else "FAIL",
    )

    # ---- 2.3 调用 restore_module ----
    ok = auto_disable.restore_module("revive_pkg")
    snap = env.snapshot_state()
    _emit(
        f"{step}.3",
        "调用 restore_module('revive_pkg')",
        fields={
            "restore_returned": ok,
            "disabled_after": list(snap["disabled"].keys()),
            "custom_nodes_dir": env.list_custom_nodes(),
            "disabled_dir": env.disabled_targets(),
        },
        result="OK" if ok and "revive_pkg" not in snap["disabled"] else "FAIL",
    )

    summary = {
        "scenario": "restore",
        "restore_ok": ok,
        "revive_pkg_present_after_restore": "revive_pkg" in env.list_custom_nodes(),
    }
    env.close()
    return summary


# ---------------------------------------------------------------------------
# 场景 3：失败场景（路径缺失）
# ---------------------------------------------------------------------------

def scenario_failure() -> dict[str, Any]:
    """模块在 NODE_CLASS_MAPPINGS 中，但物理目录已被人为删除。

    预期：``_decide`` 把它当作可禁用候选，``_disable_module`` 因路径
    缺失而 ``return False``；最终 ``state['disabled']`` 不会被写入。
    这正是真实环境中"误删目录后再触发起飞"的失败路径。
    """
    step = "3"
    env = _FakeComfyEnv(step_prefix=step)
    env.make_module("kept_pkg")
    env.make_module("ghost_pkg")
    env.add_node("KeptNode", "kept_pkg")
    env.add_node("GhostNode", "ghost_pkg")
    _emit(
        f"{step}.2",
        "注册 kept_pkg + ghost_pkg，再手动删除 ghost_pkg 的物理目录",
        fields={
            "before_delete": env.list_custom_nodes(),
        },
    )

    env.rm_module("ghost_pkg")
    _emit(
        f"{step}.3",
        "物理删除 ghost_pkg（模拟用户手动 rm -rf）",
        fields={
            "after_delete": env.list_custom_nodes(),
        },
        result="OK",
    )

    # 先让一次入队触发 scan：scan 仍能从 NODE_CLASS_MAPPINGS 里发现 ghost_pkg，
    # 但 _resolve_module_path 返回空串（路径不存在）。
    auto_disable.record_prompt([])  # 第 1 轮
    snap = env.snapshot_state()
    _emit(
        f"{step}.4",
        "首次入队（空 prompt）→ _scan_known_modules 仍能发现 ghost_pkg",
        fields={
            "known_modules": sorted(snap["known_modules"].keys()),
            "ghost_pkg_module_path": snap["known_modules"].get("ghost_pkg", {}).get(
                "module_path", ""
            ),
            "disabled_after": list(snap["disabled"].keys()),
        },
        result="ghost_pkg 出现在 known_modules 但 module_path 为空字符串",
    )

    # 继续触发到阈值
    auto_disable.record_prompt([])  # 第 2 轮
    auto_disable.record_prompt([])  # 第 3 轮：触发 _decide
    snap = env.snapshot_state()
    _emit(
        f"{step}.5",
        "第 3 轮入队：_decide 选中了 ghost_pkg 但 _disable_module 路径缺失失败",
        fields={
            "disabled_after": list(snap["disabled"].keys()),
            "ghost_pkg_in_disabled": "ghost_pkg" in snap["disabled"],
            "ghost_pkg_path_now": os.path.join(env.custom_nodes_dir, "ghost_pkg"),
            "still_exists_on_disk": os.path.exists(
                os.path.join(env.custom_nodes_dir, "ghost_pkg")
            ),
        },
        result=(
            "OK (disabled 中没有 ghost_pkg，因为 _disable_module 失败)"
            if "ghost_pkg" not in snap["disabled"]
            else "FAIL: 不应被记录为已禁用"
        ),
    )

    # ---- 3.6 排除名单：再注册一个模块并写入 exclude，验证不会被禁用 ----
    env.make_module("exempt_pkg")
    env.add_node("ExemptNode", "exempt_pkg")
    auto_disable.set_exclude(["exempt_pkg"])
    for _ in range(5):
        auto_disable.record_prompt([])
    snap = env.snapshot_state()
    _emit(
        f"{step}.6",
        "排除名单生效：exempt_pkg 命中 5 次也绝不被禁用",
        fields={
            "exclude": snap["exclude"],
            "disabled_after": list(snap["disabled"].keys()),
            "exempt_pkg_present": "exempt_pkg" in env.list_custom_nodes(),
        },
        result="OK" if "exempt_pkg" not in snap["disabled"] else "FAIL",
    )

    summary = {
        "scenario": "failure",
        "ghost_pkg_correctly_skipped": "ghost_pkg" not in snap["disabled"],
        "exempt_pkg_respected": "exempt_pkg" not in snap["disabled"],
    }
    env.close()
    return summary


# ---------------------------------------------------------------------------
# 场景 4：入队关联标识 + 干跑模式（演示新增安全边界）
# ---------------------------------------------------------------------------

def scenario_audit() -> dict[str, Any]:
    """演示 ``record_prompt(prompt_id=...)`` 与 ``state["dry_run"]``。

    - ``prompt_id`` 会写入 ``rounds`` 与最终触发禁用的 ``disabled`` 记录，
      事后可在状态文件里重建"哪个入队 → 禁用哪个目录"的因果链；
    - ``dry_run=True`` 时决策会把审计字段写好，但不实际移动目录。
    """
    step = "4"
    env = _FakeComfyEnv(step_prefix=step)

    # ---- 4.2 注册模块并带 prompt_id 入队 ----
    env.make_module("audit_pkg")
    env.add_node("AuditNode", "audit_pkg")

    for i, pid in enumerate(["prompt-A", "prompt-B", "prompt-C"], start=1):
        auto_disable.record_prompt([], prompt_id=pid)
    snap = env.snapshot_state()
    # 从状态里重建因果链
    last_round = snap["rounds"][-1]
    audit_entry = snap["disabled"].get("audit_pkg", {})
    _emit(
        f"{step}.2",
        "3 次入队都带 prompt_id；audit_pkg 首次入队即被禁用（rounds<threshold 时 recent=rounds）",
        fields={
            "last_round_prompt_id": last_round.get("prompt_id"),
            "disabled_keys": list(snap["disabled"].keys()),
            "audit_pkg_disabled_at": audit_entry.get("disabled_at"),
            "audit_pkg_prompt_id": audit_entry.get("prompt_id"),
            "audit_pkg_status": audit_entry.get("status"),
        },
        result=(
            "OK"
            if audit_entry.get("prompt_id") == "prompt-A"
            and audit_entry.get("status") == "confirmed"
            else "FAIL: prompt_id/status 未正确写入"
        ),
    )

    # ---- 4.3 验证目录已被实际移动 ----
    _emit(
        f"{step}.3",
        "实际移动发生：custom_nodes/audit_pkg 已不在，.disabled/audit_pkg 在",
        fields={
            "custom_nodes_dir": env.list_custom_nodes(),
            "disabled_dir": env.disabled_targets(),
        },
        result="OK" if "audit_pkg" not in env.list_custom_nodes() else "FAIL",
    )

    # ---- 4.4 干跑模式：fresh 环境 + dry_run=True ----
    env.close()
    env = _FakeComfyEnv(step_prefix=step)
    env.make_module("dryrun_pkg")
    env.add_node("DryRunNode", "dryrun_pkg")

    # 改写状态文件里的 dry_run 标志
    with auto_disable._state_lock:
        s = auto_disable._load_state()
        s["dry_run"] = True
        auto_disable._save_state(s)
    for pid in ["dry-prompt-1", "dry-prompt-2", "dry-prompt-3"]:
        auto_disable.record_prompt([], prompt_id=pid)
    snap = env.snapshot_state()
    audit_entry = snap["disabled"].get("dryrun_pkg", {})
    _emit(
        f"{step}.4",
        "dry_run=True：决策产生 dry_run 审计条目但不移动目录",
        fields={
            "dry_run_flag": snap.get("dry_run"),
            "dryrun_pkg_status": audit_entry.get("status"),
            "dryrun_pkg_prompt_id": audit_entry.get("prompt_id"),
            "custom_nodes_dir_still_has": "dryrun_pkg" in env.list_custom_nodes(),
            "disabled_dir_has": "dryrun_pkg" in env.disabled_targets(),
        },
        result=(
            "OK"
            if audit_entry.get("status") == "dry_run"
            and "dryrun_pkg" in env.list_custom_nodes()
            and "dryrun_pkg" not in env.disabled_targets()
            else "FAIL"
        ),
    )

    summary = {
        "scenario": "audit",
        # dryrun_pkg 在第一次入队即触发禁用（与 audit_pkg 同样的原因），
        # 所以触发的 prompt_id 是 dry-prompt-1。
        "prompt_id_persisted": audit_entry.get("prompt_id") == "dry-prompt-1",
        "dry_run_honored": audit_entry.get("status") == "dry_run",
    }
    env.close()
    return summary


# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------

SCENARIOS: dict[str, Any] = {
    "normal": scenario_normal,
    "restore": scenario_restore,
    "failure": scenario_failure,
    "audit": scenario_audit,
}


def _print_header() -> None:
    print("=" * 72)
    print("ComfyUI Auto Node Disable —— 独立诊断入口")
    print("=" * 72)
    print(f"auto_disable 模块路径: {auto_disable.__file__}")
    print(f"STATE_FILENAME       : {auto_disable.STATE_FILENAME}")
    print(f"DEFAULT_THRESHOLD    : {auto_disable.DEFAULT_THRESHOLD}")
    print(f"DEFAULT_EXCLUDE      : {list(auto_disable.DEFAULT_EXCLUDE)}")
    print(f"Python               : {sys.version.split()[0]}")
    print()


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="脱离 ComfyUI 宿主演练 auto_disable 的核心路径。"
    )
    parser.add_argument(
        "--scenario",
        choices=list(SCENARIOS) + ["all"],
        default="all",
        help="选择要跑的单个场景，默认 all。",
    )
    args = parser.parse_args(argv)

    _print_header()

    selected = (
        list(SCENARIOS) if args.scenario == "all" else [args.scenario]
    )
    results: list[dict[str, Any]] = []
    for name in selected:
        print("-" * 72)
        print(f"### 场景：{name}")
        print("-" * 72)
        try:
            results.append(SCENARIOS[name]())
        except Exception as e:  # 捕获并诊断，不要让脚本崩
            print(f"[STEP ?] 场景 {name} 抛出未处理异常: {e!r}")
            results.append({"scenario": name, "error": repr(e)})

    print("=" * 72)
    print("汇总")
    print("=" * 72)
    for r in results:
        print(json.dumps(r, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    # 让用户 Ctrl-C 时也能干净退出（临时目录在 _FakeComfyEnv.close 中清理）
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)